#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="khohang")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertphieunhap(phieunhap instance);
    partial void Updatephieunhap(phieunhap instance);
    partial void Deletephieunhap(phieunhap instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.khohangConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<phieunhap> phieunhaps
		{
			get
			{
				return this.GetTable<phieunhap>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieunhap")]
	public partial class phieunhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mapn;
		
		private string _tenpn;
		
		private System.Nullable<System.DateTime> _ngaylap;
		
		private System.Nullable<double> _tongtien;
		
		private string _mancc;
		
		private string _manv;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmapnChanging(int value);
    partial void OnmapnChanged();
    partial void OntenpnChanging(string value);
    partial void OntenpnChanged();
    partial void OnngaylapChanging(System.Nullable<System.DateTime> value);
    partial void OnngaylapChanged();
    partial void OntongtienChanging(System.Nullable<double> value);
    partial void OntongtienChanged();
    partial void OnmanccChanging(string value);
    partial void OnmanccChanged();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    #endregion
		
		public phieunhap()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mapn", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mapn
		{
			get
			{
				return this._mapn;
			}
			set
			{
				if ((this._mapn != value))
				{
					this.OnmapnChanging(value);
					this.SendPropertyChanging();
					this._mapn = value;
					this.SendPropertyChanged("mapn");
					this.OnmapnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenpn", DbType="NVarChar(50)")]
		public string tenpn
		{
			get
			{
				return this._tenpn;
			}
			set
			{
				if ((this._tenpn != value))
				{
					this.OntenpnChanging(value);
					this.SendPropertyChanging();
					this._tenpn = value;
					this.SendPropertyChanged("tenpn");
					this.OntenpnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaylap", DbType="Date")]
		public System.Nullable<System.DateTime> ngaylap
		{
			get
			{
				return this._ngaylap;
			}
			set
			{
				if ((this._ngaylap != value))
				{
					this.OnngaylapChanging(value);
					this.SendPropertyChanging();
					this._ngaylap = value;
					this.SendPropertyChanged("ngaylap");
					this.OnngaylapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Float")]
		public System.Nullable<double> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mancc", DbType="VarChar(10)")]
		public string mancc
		{
			get
			{
				return this._mancc;
			}
			set
			{
				if ((this._mancc != value))
				{
					this.OnmanccChanging(value);
					this.SendPropertyChanging();
					this._mancc = value;
					this.SendPropertyChanged("mancc");
					this.OnmanccChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(10)")]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
