using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace WindowsFormsApp1
{
    public partial class XuatKho : DevExpress.XtraEditors.XtraUserControl
    {
        DataClasses1DataContext db = new DataClasses1DataContext();
        public XuatKho()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = new WindowsFormsApp1.DataClasses1DataContext().phieunhaps;
        }
    }
}
